version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"

  tracking-service:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking-service
    depends_on:
      - mongodb
    ports:
      - "3000:3000"